modLoader="javafml"
loaderVersion="[36,)"
license="MIT"
[[mods]]
modId="craftable_creative_ability"
version="1.2"
displayName="Craftable Creative Ability"
logoFile="icon.png"
authors="xianmouyin"
description="..."
displayURL="https://www.curseforge.com/minecraft/mc-mods/craftable-creative-ability"

[[dependencies.craftable_creative_ability]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftable_creative_ability]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftable_creative_ability]]
    modId="mantle"
    mandatory=true
    versionRange="[1.6.147,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.craftable_creative_ability]]
    modId="tconstruct"
    mandatory=true
    versionRange="[3.3.0.308,)"
    ordering="NONE"
    side="BOTH"
