modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="craftable_creative_ability"
version="1.0.0"
displayName="Craftable Creative Ability"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="xianomouyin, MCreator"

[[dependencies.craftable_creative_ability]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




